### ISSUE TITLE
It is too easy to mistakenly convert from one model to another.

### ISSUE THREAD

**Issue by rec** [rec/timedata#79]
For example:

    from timedata import *
    c = Colors.red
    d = Color255(c)

I had decided that automatic conversion on each operation was too expensive to pay when nearly all calculations will occur within in the model.  _But_ I think this bug is such a footgun that we also need to make it impossible to happen by accident.

I think though that I'm not too far from a solution with what I have.

1. Many operations like e.g `add` have only very specific types that they will accept - example https://github.com/rec/timedata/blob/master/src/pyx/timedata/template/one/arithmetic.pyx  I can tighten this up to make sure this is true for all operations that logically can take "the same type" or "just related types".

2. Only methods that _must_ take _Python_ objects will be checked - e.g. https://github.com/rec/timedata/blob/master/src/pyx/timedata/template/base/sample_list.pyx#L113

3. Ideally, all of these will go through either a cast (in which case they're already the right type) or a constructor.

4. Which means that the "model conversion" _has to be done in the Cython constructor_.

This is good!  We don't actually call those Cython constructors very often.   `ColorList`s don't actually contain instances of `Color` but C++ vectors, and we don't actually produce colors unless asked to.

I'm going to follow up on this bug report with an exhaustive list of affected methods.

**Comment by rec** [comment]
The answer is "only constructors"!

**Comment by rec** [comment]
Conclusion: only need to change the constructor on `Color`

**Comment by fish2000** [comment]
Hipsters make a thing of this notion, don’t they? “Only constructors” is how Lisp works and how Scala is supposed to work (I think); I forget the more jargon-y, hashtaggish name for this that’s in use (immutable something-something?) but it’s an official _pattern_.

Anyway – personally I know at most three Lisp keywords so that’s not what I’m about, but I do do image algos in C++ (frequently intermixed with Python, these days) and I just wanted to say that yeah – regardless of trends or what they say on HN, object-wrapped data makes more sense when it’s reliably mutable only during construction.

Well, to me at least, and if at all possible – but I had to tackle a similar programming issue of my own recently, so I thought I’d throw that out there, as you seemed to have a like-minded epiphany FWIW. Erm. Yes!

**Comment by rec** [comment]
Agree completely!  Mutability is the tool of the devil.  ;-)

This worked out pretty well, with the Color* classes being immutable and the collections being mutable - and all the conversions handled by the immutables, none by the collection.
